spring.application.name=ai-chat
 
spring.ai.openai.api-key=${OPENROUTER_API_KEY}

server.port=${PORT:8080}
 
spring.ai.openai.base-url=https://openrouter.ai/api

spring.ai.openai.chat.options.model=openai/gpt-3.5-turbo
